version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
      args:
        - INSTALL_DEV_DEPENDENCIES=true
    container_name: picture_upload_service
    env_file:
      - ./env/app.dev.env
      - ./env/db.dev.env
    ports:
      - 8008:8008
    depends_on:
      - db
      - migrator
    volumes:
      - ./src/api:/home/picture_uploader/app/api
      - file_storage_volume:/home/picture_uploader/app/media

  db:
    build:
      context: .
      dockerfile: ./docker/postgres.Dockerfile
    container_name: picture_upload_postgres
    env_file:
      - ./env/db.dev.env
    volumes:
      - postgres:/var/lib/postgresql/test_data
    ports:
      - 5434:5432

  migrator:
    build:
      context: .
      dockerfile: ./docker/migrator.Dockerfile
    container_name: picture_upload_migrator
    env_file:
      - ./env/migrator.dev.env
      - ./env/db.dev.env
    depends_on:
      - db
    volumes:
      - ./src/api/infrastructure/models/changelog:/liquibase/changelog


volumes:
  postgres:
  file_storage_volume:
