#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${POSTGRES_WORK_USER} WITH ENCRYPTED PASSWORD '${POSTGRES_WORK_USER_PASSWORD}';
	CREATE DATABASE ${POSTGRES_WORK_DB};
	GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_WORK_DB} TO ${POSTGRES_WORK_USER};
EOSQL
